---
- "Brian: You're drunk. Stewie: You're sexy."
- "Stewie: Well, I'd love to stay and chat, but you're a total bitch."
- "Peter: A guy at work bought a car out of the paper. Ten years later, Bam! Herpes."
- "Peter: Okay, okay, I have an idea. I'll be Charlie and you could all be my angels. (Turns to look at an ugly woman) Except for you, you be Bosley."
