---
- "Peter: Oh my god, Brian, there's a message in my Alphabits. It says, 'Oooooo.' Brian: Peter, those are Cheerios. "
- "Lois: You're drunk again. Peter: No, I'm just exhausted 'cause I've been up all night drinking. "
- "Peter: Whoa, whoa, whoa, whoa, whoa, whoa, whoa, whoa, whoa, whoa, whoa, whoa. Lois, this isn't my Batman glass"
- "Peter: Lois, um, go get the medical dictionary and look up 'fork' and 'lung.' Lois: Why? Peter: Time is a factor, Lois. "